### ISSUE TITLE
Difference between RGBNT201 and RGBNT201-C

### ISSUE THREAD

**Issue by Bruce-GuoS** [924973292/EDITOR#6]
Thank you for your great work.
I have a question, what is the difference between  RGBNT201 and RGBNT201-C in your dataset?
Thank you~

**Comment by 924973292** [comment]
Thank you for your interest!

The data in RGBNT201 and RGBNT201-C is the same; the difference lies in the way the data is divided. RGBNT201 is customized for multimodal re-identification tasks, while RGBNT201-C is designed for cross-modal re-identification. Since this dataset includes images from multiple modalities, it can be used for various tasks. To verify the generalization of their methods, the authors of this dataset also made attempts on cross-modal tasks.

You can check the link below for more details: https://github.com/ziwang1121/IEEE/issues/4

**Comment by Bruce-GuoS** [comment]
I got it.
Thank you for your explanation and quick response~

**Comment by 924973292** [comment]
That's ok. Feel free to ask me any questions!
